# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: 
  workflow_dispatch:
    inputs:
      crd:
        description: 'CRD Headless Key:'
        required: true
        default: ''

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Download CRD
        run: curl https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi --output crd.msi
      - name: Install CRD
        run: ./crd.msi
      - name: Configure CRD
        run: ./${{ github.event.inputs.crd }}    
      - name: DONT KILL ME I HAVE A FAMILY
        run: ./time.ps1
